[package]
name = "ja-colloquial"
version = "0.2.0"
edition = "2024"
rust-version = "1.98.1"

authors = ["metastable-void"]
description = "Japanese Colloquial Christian Bible library."
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/metastable-void/ja-colloquial-rs"
include = [
    "Cargo.toml",
    "build.rs",
    "build-release.sh",
    "src/**",
    "include/**",
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
]

[lib]
crate-type = ["rlib"]

[profile.capi]
inherits = "release"
panic = "abort"
